services:
  # backend
  gameservice:
    build:
      context: .
      dockerfile: BlazorGame.GameService/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development

  #frontend
  client:
    build:
      context: .
      dockerfile: BlazorGame.Client/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - gameservice
