version: '3.8'

services:
  # Service backend
  gameservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: gameservice
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development

  # Service frontend
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    ports:
      - "5003:80"
    depends_on:
      - gameservice